### ISSUE TITLE
[delegate] msg is not correct

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-antenna-go#38]
when I update op address, it shows voting has been received. I didn't vote. 
![image](https://user-images.githubusercontent.com/448293/56480246-d11de400-64eb-11e9-899e-e28e6487c76a.png)

The message should be "your transaction has been received. Please wait for 5 mins. "

**Comment by guo** [comment]
![image](https://user-images.githubusercontent.com/448293/56480329-2823b900-64ec-11e9-90e4-2983304bcc48.png)

**Comment by raullenchai** [comment]
Is this still an issue?
