### ISSUE TITLE
Test response time

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-antenna-go#66]
After an execution is sent to our chain, fetching action receipt by hash could take 5-10s. However, because of the async call for the db indexing and other delays (internet delay), it may take more than 10s for client. We would like to do a test on mainnet to tell the average response time, min response time, and max response time by calling multi-send contracts.

**Comment by lzxm160** [comment]
tested with testnet:
```
average time: 9.4s
max 14s
min 7s
```

**Comment by lzxm160** [comment]
done
